import NextIntlProvider from '../providers/intl.provider';
import './global.css';

export const metadata = {
  title: 'Welcome to example',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <NextIntlProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </NextIntlProvider>
  );
}
